apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPRunAsNonRoot
metadata:
  name: require-nonroot-readonly
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    # gatekeeper-check — служебный ns без PodSecurity, чтобы проверить Gatekeeper отдельно
    namespaces: ["audit-zone", "gatekeeper-check"]
