# было: hostPath /etc -> emptyDir
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-fixed
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:alpine
      ports:
        - containerPort: 8080
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        # вместо hostPath — emptyDir, данные хоста поду не нужны
        - name: data
          mountPath: /data
  volumes:
    - name: tmp
      emptyDir: {}
    - name: data
      emptyDir: {}
